version: "3"

services:

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - ${MYSQL_VOLUME:-mysql-volume}:/var/lib/mysql:Z
    environment:
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DB}
    command:
    - "--max_allowed_packet=128M"
    - "--character-set-server=utf8"
    - "--collation-server=utf8_unicode_ci"

  limesurvey:
    image: acspri/limesurvey:lts
    # image: zentekmx/limesurvey
    depends_on:
    - mysql
    links:
    - mysql
    ports:
    - "3000:80"
    volumes:
    - ${LIMESURVEY_PL_VOLUME:-limesurvey-plugins-volume}:/var/www/html/plugins
    - ${LIMESURVEY_UP_VOLUME:-limesurvey-upload-volume}:/var/www/html/upload
    environment:
    - LIMESURVEY_DB_USER=${MYSQL_USER}
    - LIMESURVEY_DB_PASSWORD=${MYSQL_PASSWORD}
    - LIMESURVEY_DB_HOST=mysql
    - LIMESURVEY_DB_NAME=${MYSQL_DB}
    - LIMESURVEY_ADMIN_USER=${LIMESURVEY_ADMIN_USER}
    - LIMESURVEY_ADMIN_PASSWORD=${LIMESURVEY_ADMIN_PASSWORD}
    - LIMESURVEY_ADMIN_NAME=${LIMESURVEY_ADMIN_NAME}
    - LIMESURVEY_ADMIN_EMAIL=${LIMESURVEY_ADMIN_EMAIL}

  mailtrap:
    image: zentekmx/mailtrap
    ports:
    - "1080:1080"
    - "1025:1025"

volumes:
  mysql-volume:
  limesurvey-plugins-volume:
  limesurvey-upload-volume:
